I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 89, in script
    S "You have made a smart decision."
Exception: Sayer 'S' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 89, in script
    S "You have made a smart decision."
  File "C:\Users\csun24\Documents\GitHub\Hist12AFinal\renpy-6.99.8-sdk\renpy\ast.py", line 583, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\csun24\Documents\GitHub\Hist12AFinal\renpy-6.99.8-sdk\renpy\ast.py", line 500, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'S' is not defined.

Windows-8-6.2.9200
Ren'Py 6.99.8.959
Example 0.0
